spring:
  datasource:
    url: dbc:mysql://localhost:3306/ecommerce_db
    username: dev_user
    password: noah_1@23.Djanor
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000

logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.jdbc.core: DEBUG  # Shows SQL queries
