spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_test
    username: test_user
    password: test_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3

#logging:
#  level:
#    com.ecommerce: INFO
